-- ============================================================================
-- Platform Operations: Supporting Tables
-- Database: <PLATFORM_DB>.<ADMIN_SCHEMA>
-- ============================================================================

-- Clone audit log: tracks every clone create/drop/update operation
CREATE TABLE IF NOT EXISTS <PLATFORM_DB>.<ADMIN_SCHEMA>.CLONE_AUDIT_LOG (
    AUDIT_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CLONE_DB VARCHAR(256) NOT NULL,
    CLONE_TYPE VARCHAR(20) NOT NULL,   -- PROJECT, RELEASE, etc.
    ACTION VARCHAR(20) NOT NULL,       -- CREATE, DROP, UPDATE
    PROJECT_NAME VARCHAR(100),
    ENV_NAME VARCHAR(10),              -- DEV, QA, STAGING, etc.
    RELEASE_NAME VARCHAR(20),
    SOURCE_DB VARCHAR(256) DEFAULT '<PRODUCTION_DB>',
    STATUS VARCHAR(20) NOT NULL,       -- IN_PROGRESS, SUCCESS, FAILED
    ERROR_MSG VARCHAR(4000),
    REPOINT_SUMMARY VARCHAR(4000),
    STREAM_SUMMARY VARCHAR(4000),
    CREATED_BY VARCHAR(256) DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_LTZ(9)
);

-- Clone step log: per-step tracking for resume-from-failure support
CREATE TABLE IF NOT EXISTS <PLATFORM_DB>.<ADMIN_SCHEMA>.CLONE_STEP_LOG (
    LOG_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    AUDIT_ID NUMBER(38,0),
    CLONE_DB VARCHAR,
    STEP_NUMBER NUMBER(38,0),
    STEP_NAME VARCHAR,
    STATUS VARCHAR DEFAULT 'PENDING',  -- PENDING, IN_PROGRESS, SUCCESS, FAILED
    RESULT VARIANT,
    STARTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ(9)
);

-- RBAC mapping: schema role to functional role mapping used during clone provisioning
CREATE TABLE IF NOT EXISTS <PLATFORM_DB>.<ADMIN_SCHEMA>.RBAC_MAPPING (
    ID VARCHAR(40) NOT NULL DEFAULT UUID_STRING(),
    SCHEMA_ROLE VARCHAR(255) NOT NULL,
    ENVIRONMENT VARCHAR(40) NOT NULL,
    FUNCTIONAL_ROLE VARCHAR(255) NOT NULL,
    OPERATION VARCHAR(40) NOT NULL,    -- OWNERSHIP, USAGE, SELECT, INSERT, etc.
    EXECUTE_INDICATOR VARCHAR NOT NULL DEFAULT 'Y',
    CONSTRAINT RBAC_MAPPING_PK PRIMARY KEY (ID)
) COMMENT = 'Schema role to functional role mapping for automated RBAC provisioning';
